camunda.bpm.admin-user:
  id: admin
  password: admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: Root@123!Omar
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5Dialect
